[project]
name = "electrification-mitigation-pathways"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy (>=2.5.3,<3.0.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "matplotlib (>=3.11.2,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "plotly (>=7.0.0,<8.0.0)",
    "statsmodels (>=0.15.0,<0.16.0)",
    "pyarrow (>=25.0.1,<26.0.0)",
    "diptest (>=0.11.0,<0.12.0)",
    "pandera (>=0.33.1,<0.34.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "jupyter (<7)",
    "ruff (>=0.16.7,<0.17.0)"
]
